export const REGISTER_PATIENT = "REGISTER_PATIENT";
export const GET_PATIENT = "GET_PATIENT";
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_PATIENT_ONE = "GET_PATIENT_ONE";
export const PATIENT_SUBMIT = "PATIENT_SUBMIT";
export const GET_ANALYTICS = "GET_ANALYTICS";
